@echo off

set UE4_PATH="{{UE4_PATH}}"
set PROJECT_NAME={{PROJECT_NAME}}
set PROJECT_PATH={{PROJECT_PATH}}\%PROJECT_NAME%
set UPROJECT_FILE=%PROJECT_PATH%\%PROJECT_NAME%.uproject
set GAME_PATH={{GAME_PATH}}\Content\Ascentroid\Paks